---

name: "Build"
run-name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SOLUTION_NAME: 'StopWatch.sln'
  TEST_LOGGER: 'trx;logfilename=testResults.trx'

concurrency:
  group: build-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build in ${{ matrix.configuration }} Mode"
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
    steps:
      - id: checkout
        name: "Checkout"
        uses: actions/checkout@v3

      - id: setup-dotnet
        name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - id: restore
        name: "Restore"
        run: nuget restore "${SOLUTION_NAME}"

      - id: build
        name: "Build"
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore "${SOLUTION_NAME}"

      - id: test
        name: "Test"
        run: dotnet test --configuration ${{ matrix.configuration }} --no-restore --no-build --logger "${TEST_LOGGER}" "${SOLUTION_NAME}"

      - id: upload-test-artifact
        if: always() && steps.test.outcome != 'skipped'
        name: "Archive Test Results"
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (${{ matrix.configuration }})
          path: '**/*.trx'
